# payment-service — Postgres: hotel_payments
server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotel_payments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
